config/routes.rb
Rails.application.routes.draw do
  resources :heros
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/hero.rb
class Hero < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/heros_controller.rb
class HerosController < ApplicationController
  before_action :set_hero, only: %i[ show edit update destroy ]

  # GET /heros or /heros.json
  def index
    @heros = Hero.all
  end

  # GET /heros/1 or /heros/1.json
  def show
  end

  # GET /heros/new
  def new
    @hero = Hero.new
  end

  # GET /heros/1/edit
  def edit
  end

  # POST /heros or /heros.json
  def create
    @hero = Hero.new(hero_params)

    respond_to do |format|
      if @hero.save
        format.html { redirect_to hero_url(@hero), notice: "Hero was successfully created." }
        format.json { render :show, status: :created, location: @hero }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @hero.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /heros/1 or /heros/1.json
  def update
    respond_to do |format|
      if @hero.update(hero_params)
        format.html { redirect_to hero_url(@hero), notice: "Hero was successfully updated." }
        format.json { render :show, status: :ok, location: @hero }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @hero.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /heros/1 or /heros/1.json
  def destroy
    @hero.destroy!

    respond_to do |format|
      format.html { redirect_to heros_url, notice: "Hero was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hero
      @hero = Hero.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def hero_params
      params.require(:hero).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/heros_helper.rb
module HerosHelper
end

app/views/heros/_form.html.erb
<%= form_with(model: hero) do |form| %>
  <% if hero.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(hero.errors.count, "error") %> prohibited this hero from being saved:</h2>

      <ul>
        <% hero.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/heros/_hero.html.erb
<div id="<%= dom_id hero %>">
  <p>
    <strong>Name:</strong>
    <%= hero.name %>
  </p>

</div>

app/views/heros/edit.html.erb
<% content_for :title, "Editing hero" %>

<h1>Editing hero</h1>

<%= render "form", hero: @hero %>

<br>

<div>
  <%= link_to "Show this hero", @hero %> |
  <%= link_to "Back to heros", heros_path %>
</div>

app/views/heros/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Heros" %>

<h1>Heros</h1>

<div id="heros">
  <% @heros.each do |hero| %>
    <%= render hero %>
    <p>
      <%= link_to "Show this hero", hero %>
    </p>
  <% end %>
</div>

<%= link_to "New hero", new_hero_path %>

app/views/heros/new.html.erb
<% content_for :title, "New hero" %>

<h1>New hero</h1>

<%= render "form", hero: @hero %>

<br>

<div>
  <%= link_to "Back to heros", heros_path %>
</div>

app/views/heros/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @hero %>

<div>
  <%= link_to "Edit this hero", edit_hero_path(@hero) %> |
  <%= link_to "Back to heros", heros_path %>

  <%= button_to "Destroy this hero", @hero, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Tour Of Heroes" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>